/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import datos.Contacto;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.Libreta;

/**
 *
 * @author JEKSER
 */
public class Gui extends javax.swing.JFrame {

    private Libreta libreta;
    private Contacto contactoSelect;
    public Gui() {
        initComponents();
        this.libreta=new Libreta();
        this.cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtNombre = new javax.swing.JTextField();
        jtTelefono = new javax.swing.JTextField();
        jtCorreo = new javax.swing.JTextField();
        chbFavorito = new javax.swing.JCheckBox();
        btnGuardar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListaContactos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Nombre  :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 70, 20);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Telefono :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 70, 70, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Correo :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 100, 60, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Es favorito? :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 130, 90, 14);

        jtNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtNombre);
        jtNombre.setBounds(120, 40, 250, 23);

        jtTelefono.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtTelefono);
        jtTelefono.setBounds(120, 70, 140, 23);

        jtCorreo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jtCorreo);
        jtCorreo.setBounds(120, 100, 140, 23);

        chbFavorito.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        chbFavorito.setText("Si");
        getContentPane().add(chbFavorito);
        chbFavorito.setBounds(120, 130, 35, 25);

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar);
        btnGuardar.setBounds(410, 40, 90, 25);

        btnBorrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBorrar.setText("borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar);
        btnBorrar.setBounds(410, 100, 90, 25);

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSalir.setText("salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir);
        btnSalir.setBounds(450, 370, 70, 25);

        btnEditar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEditar.setText("editar");
        getContentPane().add(btnEditar);
        btnEditar.setBounds(410, 70, 90, 25);

        tbListaContactos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListaContactosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListaContactos);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 160, 520, 190);

        setSize(new java.awt.Dimension(563, 450));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        salir();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        adicionarContacto();
        cargarDatos();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void tbListaContactosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListaContactosMouseClicked
        cargarContacto();
    }//GEN-LAST:event_tbListaContactosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JCheckBox chbFavorito;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtCorreo;
    private javax.swing.JTextField jtNombre;
    private javax.swing.JTextField jtTelefono;
    private javax.swing.JTable tbListaContactos;
    // End of variables declaration//GEN-END:variables
    
    private void adicionarContacto(){
        Contacto c=new Contacto();
        c.setNombre(jtNombre.getText());        
        c.setTelefono(Long.parseLong(jtTelefono.getText().isEmpty()? "0":jtTelefono.getText()));
        c.setCorreo(jtCorreo.getText());
        c.setFavorito(chbFavorito.isSelected());
        if(libreta.adicionarContacto(c)){
            JOptionPane.showMessageDialog(this,"Contacto Guardado con exito","Informacion",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Error al guardar contacto","Alerta",JOptionPane.ERROR_MESSAGE);
        }        
    }
    
    private void editarContacto(){
        Contacto c=new Contacto();        
        c.setNombre(jtNombre.getText());        
        c.setTelefono(Long.parseLong(jtTelefono.getText().isEmpty()? "0":jtTelefono.getText()));
        c.setCorreo(jtCorreo.getText());
        c.setFavorito(chbFavorito.isSelected());
        if(libreta.editarContacto(c)){
            JOptionPane.showMessageDialog(this,"Datos actualizados con exito","Informacion",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this,"Error al actualizar datos","Alerta",JOptionPane.ERROR_MESSAGE);
        } 
    }
    
    private void borrarContacto(){
        
        //libreta.borrarContacto(contacto)
        
    }
    
    private void cargarDatos(){
        ArrayList<Contacto> lista=libreta.getContactos();
        DefaultTableModel modelo=new DefaultTableModel();
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE COMPLETO");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("CORREO");
        modelo.addColumn("FAVORITO");
        
        for(Contacto contacto: lista){
            Object[] datos={
                contacto.getIdentificador(),
                contacto.getNombre(),
                contacto.getTelefono(),
                contacto.getCorreo(),
                contacto.isFavorito()==true ? "si":"no"                
            };
            modelo.addRow(datos);
        }
        this.tbListaContactos.setModel(modelo);
    }
    
    private void cargarContacto(){        
        int fila=tbListaContactos.getSelectedRow();
        Long id= (Long) tbListaContactos.getValueAt(fila,0);
        contactoSelect=libreta.buscarContacto(id);
        
        jtNombre.setText(contactoSelect.getNombre());
        jtCorreo.setText(contactoSelect.getCorreo());
        jtTelefono.setText(contactoSelect.getTelefono().);
        
        
    }
    
    
    private void salir(){
        System.exit(0);
    }
}
